POST http://localhost:3000/form
Content-Type: application/json

{
    "name":"Pandu",
    "phone":"123",
    "email":"abc@gmail.com",
    "query":"Divorce",
    "dispute":"Civil",
    "freetime":"5 pm to 6 pm"
}